variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

image: maven:3-openjdk-17

cache:
  paths:
    - .m2/repository

stages:
  - build
  - test
  - lint
  - deploy

build:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS clean install --settings ci_settings.xml'
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

test:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS clean test --settings ci_settings.xml'
  artifacts:
    paths:
      - target/test-classes
      - target/site/jacoco
    expire_in: 1 hour

lint:
  stage: lint
  script:
    - 'mvn checkstyle:check --settings ci_settings.xml || echo "Checkstyle"'
  allow_failure: true
  artifacts:
    paths:
      - target/checkstyle-result.xml
    when: always

deploy:jdk17:
  stage: deploy
  script:
    - |
      if [ ! -f ci_settings.xml ]; then
        echo "CI settings missing! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/packages/maven_repository/index.html"
      fi
    - 'mvn $MAVEN_CLI_OPTS deploy --settings ci_settings.xml'
